{% set name = "pyopencl" %}
{% set version = "2022.2.3" %}
{% set build_number = 0 %}
{% set sha256 = "21da5f08aabbc2b2fdc81466ffaac07c1db94b1f47a95bc57f633b55590ccba2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - osx_flags.diff

build:
  number: {{ build_number }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('m2w64_cxx') }}      # [win and vc<14]
  host:
    - python
    - libpython      # [win and vc<14]
    - setuptools
    - pybind11
    - numpy
    - ocl-icd      # [linux]
    - khronos-opencl-icd-loader      # [win or osx]

  run:
    - python
    - {{ pin_compatible("numpy") }}
    - pytools
        # for pkg_resources
    - setuptools
    - mako
    - platformdirs
    - khronos-opencl-icd-loader      # [win or osx]
    - ocl-icd      # [linux]

test:
  requires:
    - pytest
    - pocl  >=0.14      # [linux or osx]
    - intel-opencl-rt   # [win64 or linux64]
  imports:
    - {{ name }}
  source_files:
    - test
    - examples/demo.py
  commands:
    - echo %OCL_ICD_FILENAMES%  # [win]
    - python examples/demo.py
    # tests crash on aarch64/ppc64le
    - python -m pytest -v test/ -k not test_slice   # [not (linux and (aarch64 or ppc64le))]

about:
  home: https://pypi.python.org/pypi/pyopencl
  doc_url: https://documen.tician.de/pyopencl
  dev_url: https://github.com/inducer/pyopencl
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for OpenCL
  description: |
    PyOpenCL lets you access GPUs, multi-core CPUs, and other massively
    parallel compute devices from Python, through the OpenCL parallel
    compute interface.

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - matthiasdiener
