{% set name = "pyopencl" %}
{% set version = "2020.3" %}
{% set build_number = 0 %}
{% set sha256 = "4aa3031c17fc99aa2f3018ef2c9e1d535c3cfdc7a01bb987b1ea3826ef42bd59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - osx_flags.diff
    - skip-rect-copy-tests-on-apple.patch

build:
  number: {{ build_number }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('m2w64_cxx') }}      # [win and vc<14]
  host:
    - python
    - libpython      # [win and vc<14]
    - setuptools
    - pybind11
    - numpy
    - ocl-icd      # [linux]
    - khronos-opencl-icd-loader      # [win or osx]

  run:
    - python
    - {{ pin_compatible("numpy") }}
    - pytools
        # for pkg_resources
    - setuptools
    - six
    - mako
    - appdirs
    - khronos-opencl-icd-loader      # [win or osx]
    - ocl_icd_wrapper_apple      # [osx]
    - ocl-icd      # [linux]

test:
  requires:
    - pytest
    - pocl  >=0.14      # [linux]
  imports:
    - {{ name }}
  source_files:
    - test
  commands:
    # apple implementation on 10.14 is buggy. So skip test_can_build_and_run_binary
    - cd test && python -m pytest -k "not test_can_build_and_run_binary"       # [osx]

about:
  home: http://pypi.python.org/pypi/pyopencl
  doc_url: https://documen.tician.de/pyopencl
  dev_url: http://github.com/inducer/pyopencl
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for OpenCL
  description: |

    PyOpenCL lets you access GPUs, multi-core CPUs, and other massively
    parallel compute devices from Python, through the OpenCL parallel
    compute interface.

extra:
  recipe-maintainers:
    - inducer
    - isuruf
