{% set name = "pyopencl" %}
{% set version = "2025.1" %}
{% set build_number = 1 %}
{% set sha256 = "0116736d7f7920f87b8db4b66a03f27b1d930d2e37ddd14518407cc22dd24779" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - nanobind >=1.9.2                       # [build_platform != target_platform]
    - scikit-build-core >=0.9.3              # [build_platform != target_platform]
    - cmake
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make  # [unix]
  host:
    - python
    - pip
    - setuptools
    - nanobind >=1.9.2
    - scikit-build-core >=0.9.3
    - numpy
    - libopencl-devel
  run:
    - python
    - pytools
    - mako
    - platformdirs

test:
  requires:
    - pytest
    - pocl  >=0.14      # [linux or osx]
    - oclgrind          # [win]
    # See https://github.com/conda-forge/pocl-feedstock/pull/96:
    - ld64 <711         # [osx]
  imports:
    - {{ name }}
  source_files:
    - test
    - examples/demo.py
  commands:
    - echo %OCL_ICD_FILENAMES%  # [win]
    - python examples/demo.py
    # tests crash on aarch64/ppc64le
    - python -m pytest -v test/   # [linux64 or osx]

about:
  home: https://pypi.python.org/pypi/pyopencl
  doc_url: https://documen.tician.de/pyopencl
  dev_url: https://github.com/inducer/pyopencl
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for OpenCL
  description: |
    PyOpenCL lets you access GPUs, multi-core CPUs, and other massively
    parallel compute devices from Python, through the OpenCL parallel
    compute interface.

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - matthiasdiener
