{% set name = "pyopencl" %}
{% set version = "2018.2.1" %}
{% set build_number = 1000 %}
{% set sha256 = "5ed40baccb493e8e9ac394f15c64871954d234fd6d9250c50bee1466d8bd8e48" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: {{ build_number }}
    features:
        - osx_pocl_opencl   # [pyopencl_variant == 'pocl']

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('m2w64_cxx') }}  # [win and vc<14]
    host:
        - python
        - libpython  # [win and vc<14]
        - setuptools
        - pybind11
        - numpy
        - ocl-icd  # [linux]
        - khronos-opencl-icd-loader  # [win]
        - osx-pocl-opencl   # [pyopencl_variant == 'pocl']
        - pocl >=1.1    # [pyopencl_variant == 'pocl']
        - clangdev  # [pyopencl_variant == 'pocl']
        - libcxx    # [pyopencl_variant == 'pocl']

    run:
        - python
        - {{ pin_compatible("numpy") }}
        - pytools
        # for pkg_resources
        - setuptools
        - six
        - mako
        - appdirs
        - khronos-opencl-icd-loader  # [win]
        - ocl-icd  # [linux]
        - osx-pocl-opencl   # [pyopencl_variant == 'pocl']
        - {{ pin_compatible("pocl") }}  # [pyopencl_variant == 'pocl']
        - {{ pin_compatible("libcxx") }}    # [pyopencl_variant == 'pocl']

test:
    requires:
        - pytest
        - pocl  >=0.14  # [linux]
    imports:
        - {{ name }}
    source_files:
        - test

{# FIXME: Enable tests on OSX POCL build #}
    commands:
        - cd test && python -m pytest  # [osx and pyopencl_variant != 'pocl']

about:
    home: http://pypi.python.org/pypi/pyopencl
    doc_url: https://documen.tician.de/pyopencl
    dev_url: http://github.com/inducer/pyopencl
    license: MIT
    license_file: LICENSE
    summary: Python wrapper for OpenCL
    description: |

        PyOpenCL lets you access GPUs, multi-core CPUs, and other massively
        parallel compute devices from Python, through the OpenCL parallel
        compute interface.

extra:
    recipe-maintainers:
        - inducer
