{% set name = "pyopencl" %}
{% set version = "2021.2.2" %}
{% set build_number = 0 %}
{% set sha256 = "50876f16624bc623fa2eff98a91259761b51471e186f535d4d4e7bce58292f0c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - osx_flags.diff

build:
  number: {{ build_number }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('m2w64_cxx') }}      # [win and vc<14]
  host:
    - python
    - libpython      # [win and vc<14]
    - setuptools
    - pybind11
    - numpy
    - ocl-icd      # [linux]
    - khronos-opencl-icd-loader      # [win or osx]

  run:
    - python
    - {{ pin_compatible("numpy") }}
    - pytools
        # for pkg_resources
    - setuptools
    - mako
    - appdirs
    - khronos-opencl-icd-loader      # [win or osx]
    - ocl-icd      # [linux]

test:
  requires:
    - pytest
    - pocl  >=0.14      # [linux or osx]
    - oclgrind          # [win]
  imports:
    - {{ name }}
  source_files:
    - test
    - examples/demo.py
  commands:
    - echo %OCL_ICD_FILENAMES%  # [win]
    - python examples/demo.py
    # Apple CL implementation is poor and will crash randomly. Only test the array.
    - cd test && python -m pytest test_array.py      # [osx]

about:
  home: http://pypi.python.org/pypi/pyopencl
  doc_url: https://documen.tician.de/pyopencl
  dev_url: http://github.com/inducer/pyopencl
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for OpenCL
  description: |
    PyOpenCL lets you access GPUs, multi-core CPUs, and other massively
    parallel compute devices from Python, through the OpenCL parallel
    compute interface.

extra:
  recipe-maintainers:
    - inducer
    - isuruf
