matrix:
- [[OSX_VARIANT, native]]
- [[OSX_VARIANT, pocl]]
travis:
  secure:
    BINSTAR_TOKEN: HXz5+M9EU9vhb6X/4BJRtJ+6oY+SpRtMB1vTOUphC1XydbV8RfXjbXxRuj+3dg5P+HMd4J5WKhGU8NsItcki9Zn6tx+djgnBmA+J06VzF3ILEtoCPuMluPH5o+U37IWTE0YV3vHprUoZ6/G4AGt5iL+34IejtGNuRnsm/udRR9qWsMtLppL6osA8XeKl4Rq7hg52O+Ktm5i5vbwVlW3Sj3EMQWCWKzMId/KakTFzvGDeKF/i/uy2PRXy50eCJvzzqseO6re9P1piJ+RpW1VejQ6U0GmpTNVmgf+yli5xrCjPHF6q1Trm4jf46rsqXEC1ZFprLvwjGdZgLuBJGYeO9vSdJFzn4hGEfpvknumWkPVhdg07RsEfaK1+63P+bR3zZzPwKsHXiG1n2wx6yadHvNmhpgXT4REQCAcbBpWikPeoGkLNUhV/tLl74ZxSCI3c/SLleC9DhGGE8NPqu9rV0l0VTXU6sg4O07+lZjex/gpCvYypa5hAPk9ROHhr8qTJhWbzW/iL6bGY/3oz1JAKmBr0JlVO+OxhtwwbpztEaf7qbDnCYIR5vRewpd6TyliU/4JRIv8K8ydTK5o42/dlDpWEG22TrmKDCcEQWSD9tOn0j6DTUVUDV3hRRifpKijG3So7KVhXNaSuObSELu6l2h4J4JOaARiDdNju9d0/ua8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
