version: 2

jobs:
  build__OSX_VARIANT_native__CONDA_PY_27:
    working_directory: ~/test
    machine: true
    environment:
      - OSX_VARIANT: "native"
      - CONDA_PY: "27"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "OSX_VARIANT=${OSX_VARIANT}"
            echo "CONDA_PY=${CONDA_PY}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh
  build__OSX_VARIANT_native__CONDA_PY_35:
    working_directory: ~/test
    machine: true
    environment:
      - OSX_VARIANT: "native"
      - CONDA_PY: "35"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "OSX_VARIANT=${OSX_VARIANT}"
            echo "CONDA_PY=${CONDA_PY}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh
  build__OSX_VARIANT_native__CONDA_PY_36:
    working_directory: ~/test
    machine: true
    environment:
      - OSX_VARIANT: "native"
      - CONDA_PY: "36"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "OSX_VARIANT=${OSX_VARIANT}"
            echo "CONDA_PY=${CONDA_PY}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build__OSX_VARIANT_native__CONDA_PY_27
      - build__OSX_VARIANT_native__CONDA_PY_35
      - build__OSX_VARIANT_native__CONDA_PY_36
